sudo: requires 

services: 
 - docker

language: python

install: sudo -E ./install to-infn/dev || true

script: |
  set -ex
  PREFIX=/opt/plancton/.plancton
  dielog() {
    sudo cat $PREFIX/log/plancton.log
    exit 1
  }
  [[ -f $PREFIX/plancton.pid ]] || dielog
  sudo kill -0 $(sudo cat $PREFIX/plancton.pid) || dielog
