sudo: requires 
services: 
 - docker
language: python

before_install:
 - sudo apt-get install docker-engine
 - sudo apt-get install git
 - sudo apt-get install python-pip

install: sudo ./install to-infn/dev

